import { Button, VerticalBox , AboutSlint, Slider, Switch, ListView, CheckBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 480px;
    height: 320px;
    in-out property <float> slider-value <=> slider.value ;
    callback request-increase-value();
    VerticalBox { 
        HorizontalLayout {
            Text {
                text: "Counter: \{slider.value}";
                Switch {
                    text: "Switch"; 
                }
                CheckBox {
                    text: "CheckBox";
                    x: 360px;
                    y: -6px;
                }
            }
        }
        Button {
            text: "Increase value";
            clicked => { 
                root.request-increase-value();
            }
        }
        slider := Slider {
            minimum: 0;
            value: 42;
            maximum: 100;
        }
        AboutSlint { }
     }
}
