import { Button, VerticalBox , AboutSlint, Slider } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 480px;
    height: 320px;
    in-out property <float> slider-value <=> slider.value ;
    callback request-increase-value();
    VerticalBox { 
        Text {
            text: "Counter: \{slider.value}";
        }
        Button {
            text: "Increase value";
            clicked => { 
                root.request-increase-value();
            }
        }
        slider := Slider {
            minimum: 0;
            value: 42;
            maximum: 100;
        }
        AboutSlint { }
     }
}
